name: ğŸš€ Run SMSBoom in Action

# è§¦å‘ Action çš„æ¡ä»¶
on: 
  # å®šæ—¶è§¦å‘ å‚è€ƒ https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#schedule
  # schedule:
  #     - cron: '30 5 * * 1,3'
  #     - cron: '30 5 * * 2,4'
  # æ‰‹åŠ¨è§¦å‘
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ç­¾å‡ºé¡¹ç›®ä»£ç 
      - uses: actions/checkout@v3
      # è®¾ç½® py3.8 ç¯å¢ƒ
      - name: ğŸš€ è®¾ç½®Python 3.11ç¯å¢ƒ
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      
      - name: ğŸš€ å®‰è£…ç¯å¢ƒ
        # æ­¤å¤„å¯ä»¥è‡ªå®šä¹‰å‘½ä»¤è¡Œè¿è¡Œå‚æ•°.æ›¿æ¢æ‰‹æœºå·
        run: |
          pip3 install -r requirements.txt
          pip3 install pyinstaller
          echo "â„¹ï¸ [I]ç¯å¢ƒå®‰è£…ï¼šå®Œæˆ"
      - name: ğŸ“¦ æ‰“åŒ…
        run: |
          pyinstaller -F smsboom.py
          echo "â„¹ï¸ [I]æ‰“åŒ…ï¼šå®Œæˆ"
          echo "â„¹ï¸ [I]å½“å‰ç›®å½•:"
          ls
          echo "â„¹ï¸ [I]distç›®å½•:"
          cd dist

